### ISSUE TITLE
[NEW FEATURE] Return flightroute for search with registration

### ISSUE THREAD

**Issue by MikeW27** [mrjackwills/adsbdb#14]
I would like to know the current position and flight details for a specific aircraft registration.
Would it be possible to include the current flightroute, callsign etc when looking up https://api.adsbdb.com/v0/aircraft/[MODE_S || REGISTRATION] (without knowing the current callsign)?

**Comment by mrjackwills** [comment]
I'm sorry but such a feature is out of the scope of this project, even though I obviously agree that it would be a great idea :(
