### ISSUE TITLE
[DATA] missing G-POLU, G-HMGD, G-HMGE

### ISSUE THREAD

**Issue by taeh98** [mrjackwills/adsbdb#27]
**Url of request**
https://api.adsbdb.com/v0/aircraft/G-POLU
https://api.adsbdb.com/v0/aircraft/G-HMGD
https://api.adsbdb.com/v0/aircraft/G-HMGE

**Why was the data wrong**
No data - unknown aircraft

**Source of information**
https://www.caa.co.uk/aircraft-register/g-info/search-g-info/

**Additional context**
N/A

**Comment by mrjackwills** [comment]
I have tried to incorporate as much as possible from the UK registry in the 0.3.0 release.

Although their API is slightly annoying, 14,388 new UK aircraft are now in the adsbdb database, including all the ones listed here
