### ISSUE TITLE
[DATA] missing aircraft

### ISSUE THREAD

**Issue by RFXdk** [mrjackwills/adsbdb#30]
**Url of request**
[What was the url of the request that was made]
(https://api.adsbdb.com/v0/aircraft/se-rta)

**Why was the data wrong**
Which aspect of the response data was incorrect? Aircraft not found

**Source of information**
If possible, would you be able to provide a link that shows the correct data? https://www.flightradar24.com/data/aircraft/se-rta#

**Additional context**
Find many missing planes, especially from Norwegian.

BTW, thanks a lot for providing this service, really a nice, clean, free and excellent API - Thank you !

I am new to this, so I could be wrong, but A/C lookup have succeeded many times, but also failed sometimes as described above.

Best regards,
Peter

**Comment by mrjackwills** [comment]
Thanks, this aircraft - along with 222,129 others, have now been inserted in to the adsbdb database
