### ISSUE TITLE
[DATA] VH & ZK, DQ, etc

### ISSUE THREAD

**Issue by hodgkiss** [mrjackwills/adsbdb#32]
**Url of request**
[What was the url of the request that was made]
(https://api.adsbdb.com/v0/aircraft/VH-X4A)

**Why was the data wrong**
Which aspect of the response data was incorrect?
No Data, VH is downloadable like the N-reg system, they include numbers now! -see below- 

**Source of information**
[If possible, would you be able to provide a link that shows the correct data?]
(https://www.casa.gov.au/aircraft/aircraft-registration/data-files-registered-aircraft#Tipstodownloadthefiles)

**Additional context**
This can be applied to other sites like ZK, DQ.
Need to introduce prefix filter to different database to allow for no/low change to store info.

**Comment by mrjackwills** [comment]
It's taken a long time to look at these, I'm working on a big data update at the moment.

As far as I could tell, the linked data doesn't proved the aircraft's MODE_S hex code, which at the moment is kind of vital to how the api works. I'm guessing this data isn't also available somewhere else on the casa site?

**Comment by mrjackwills** [comment]
I have tried to incorporate as much as possible from the Austrailian data file in the v0.3.0 release
