### ISSUE TITLE
Feature Proposal: API Documentation

### ISSUE THREAD

**Issue by RijulTP** [mrjackwills/adsbdb#39]
Hi there! I'd love to help set up API documentation for your project.  
I've been working with a documentation platform called LiveAPI, and I can get everything set up for you at no cost.

All we ask in return is some feedback or a brief testimonial.  
Feel free to check it out here: [LiveAPI](https://hexmos.com/liveapi).

Also, here is a brief demo of LiveAPI in action.

You can try out the API with the “Try It” button and get the response right away.

![image](https://github.com/user-attachments/assets/2155924c-23f3-4690-8e1b-f8263751de60)
Plus, if you want to use the API in a specific language, our built-in code generator makes that super easy.

![image](https://github.com/user-attachments/assets/223a4515-39db-41c6-9291-66919fd4ed53)

**Comment by mrjackwills** [comment]
Thanks, but it's not something that would be appropriate at the moment.
