### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Latebat** [mrjackwills/adsbdb#9]
the coming from and going to airports are the same on most of the flights

**Comment by mrjackwills** [comment]
Can you give an example of a flight where this is happening, so far I have not found it to be true in my current use case

**Comment by Latebat** [comment]
https://api.adsbdb.com/v0/aircraft/a658a1?callsign=GTI4766

**Comment by mrjackwills** [comment]
Looks like a cargo flight, which change their origin and destination frequently. Which origin + destination do you think it should be changed to, the latest flight was Frankfurt (HHN) to Chicago (RFD), but has been other pairs recently. 
adsbdb is static in this regard, the data in the database doesn't/can't get updated with human (my) interaction

**Comment by Latebat** [comment]
Thanks for the help but we decided to remove it from our application due to the inaccurate flightroute data we have been comparing the data to https://globe.adsbexchange.com/ alot of it didnt match what they had
